import { Inter } from 'next/font/google'
import './globals.css'
import { ProvidersTheme } from './providers'
import { Providers } from '@/store/provider'
import {store} from '@/store/store'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers store={store}>
          <ProvidersTheme>
            {children}
          </ProvidersTheme>
        </Providers>
      </body>
    </html>
  )
}
